PennyPence/pennypence-drf-backend

- back/settings.py
> feat: 카카오 소셜 로그인

- questions/admin.py
- questions/apps.py
- questions/models.py
- questions/serializers.py
- questions/tests.py
- questions/urls.py
- questions/views.py
- test.py
QnA 앱 생성하고, models, serializers, urls, views 베이스 코드만 작성했습니다.
close #15
> feat: QnA 앱 생성 및 베이스코드 작성

- questions/models.py
- questions/serializers.py
- questions/urls.py
- questions/views.py
models.py
Question, Comment 모델 최신순으로 출력되도록 변경.
serializers.py
좋아요 갯수 및 성능 개선을 위해 함수 및 like_count 추가.
views.py
글 상세 보기 api GET 요청시, 글의 상세목록, 댓글 및 대댓글 목록, 좋아요 갯수 까지 추가 되도록 변경.
글과 댓글의 like 기능 추가.
LikeViewSet에 질문의 좋아요 목록 댓글의 좋아요 목록 출력 할 수 있도록 추가.
close #18
> refact: 코드 리팩토링

- accounts/models.py
- accounts/serializers.py
- accounts/urls.py
- accounts/views.py
- serializers 작성
- 카카오 사용자 정보 nickname, profile_img 저장
close #20
> feat: 카카오 로그인 serializers 작성 #20

- accounts/serializers.py
- accounts/urls.py
- accounts/views.py
> feat: 프로필 페이지 유저 정보 출력 #28

- accounts/serializers.py
- accounts/views.py
> feat: 프로필 수정 구현 #31

- auction/admin.py
- auction/apps.py
- auction/models.py
- auction/serializers.py
- auction/tests.py
- auction/urls.py
- auction/views.py
- back/settings.py
- back/urls.py
- communities/models.py
- communities/serializers.py
- communities/urls.py
- communities/views.py
- auction 앱은 item model 과 inventory model이 완성되면 주석 풀고 테스트해야함.
- communities 앱은 accounts 앱이 완성 된 후에 serializers 적용하면 완성.
- in progress #33
> feat: 옥션 앱 베이스 코드 작성 및 communities 코드 약간 수정

- accounts/models.py
accounts 모델의 유저 아이템 목록(ManyToManyField) 필드 생성
close #38
> feat: accounts의 유저 아이템 목록 필드 생성 #38

- assets/sector_percentage.py
- assets/views.py
40일차 주가를 DB에 삽입하기 위해 코드를 일부분 수정합니다
> 섹터 DB저장 코드 수정 #41

- assets/urls.py
- assets/views.py
News Detail 메서드와 url 코드를 추가합니다
> feat: News Detail 메서드와 url 코드 추가 #42

- accounts/managers.py
- accounts/models.py
username 오류를 위한 managers.py 작성
> fix: managers.py 작성

- back/settings.py
시크릿키 설정때문에 생긴 오류였습니다.. 죄송합니다 :(
> fix: settings 오류 해결

- back/settings.py
- requirements.txt
- settings.py 주석처리 한거 변경
- dj-rest-auth 3.0.0 > 2.2.5 변경 dj-rest-auth 지우고 다시 깔아주세요~
> fix: settings.py 변경, requirements dj-rest-auth 변경

- accounts/serializers.py
- accounts/urls.py
- accounts/views.py
> feat: 닉네임 수정 및 중복확인 기능 구현 #63

- accounts/models.py
- accounts 모델에서 유저의 뉴스 읽음 여부를 구현하기 위해 ManytoMany 필드를 User_News 클래스로 확장 및 read 변수로 Boolean 필드 추가
- 일차 테이블을 ForeignKey로 끌어오기
close #80
> feat: 유저의 뉴스 읽음 여부 필드 추가 #80

- assets/serializers.py
- assets/urls.py
- assets/views.py
- 매수 페이지 url 설정
- 매수 로직 코드 작성
close #82
> feat: 매수 페이지 출력 및 매수 코드 작성 #82

- assets/models.py
- assets/views.py
> feat: 매수 로직 작성 #86

- assets/views.py
> feat: 자동매도 후 랭킹갱신 코드 작성 #88

- .github/workflows/deploy.yml
- back/settings.py
- 버킷이름 오입력으로 인한 재설정
- AWS beanstalk 버킷이름 수정
close #92
> feat: 배포 환경변수 추가 #91

- back/settings.py
> feat: DEBUG False로 변경 #92

- .github/workflows/deploy.yml
> feat: deploy.yml 수정 #93

- back/settings.py
github action 엑세스키, 시크릿키 재설정
close #97
> feat: github action 엑세스키, 시크릿키 재설정 #96
